apiVersion: v1
kind: Service
metadata:
  name: task
spec:
  type: LoadBalancer
  selector:
    app: task
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deploy
spec:
  selector:
    matchLabels:
      app: task
  replicas: 3
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task-pod
        image: krravindra/techolution
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10